import type { JSONSchema } from "json-schema-to-ts"

export default {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "DO NOT CHANGE THIS FILE MANUALLY AS IT WILL BE OVERWRITTEN BY A GITHUB ACTION. If you want to modify the list of tags, edit the files in (or add new files to) ts/content/tags instead!",
  "type": "string",
  "enum": [
    "add",
    "advanced",
    "allNegative",
    "allPositive",
    "any",
    "Apply concepts to novel situations",
    "basic",
    "Build mathematical models",
    "calculate",
    "Calculate summary statistics",
    "coeffAbsZeroToHundred",
    "coeffAbsZeroToHundredTousand",
    "coeffAbsZeroToMillion",
    "coeffAbsZeroToTen",
    "coeffAbsZeroToTenTousand",
    "coeffAbsZeroToTousand",
    "Collect and organize data",
    "complex",
    "concreteFunctions",
    "concreteGraphs",
    "concreteNumbers",
    "Connect related concepts",
    "Convert real-world situations to mathematical form",
    "coordinateAxes",
    "coordinatePlane",
    "coordinates",
    "Create visual representations",
    "decimalNumbers",
    "Define mathematical terms and relationships",
    "degreeHigher",
    "degreeOfPolynomial",
    "degreeOne",
    "degreeThree",
    "degreeTwo",
    "degreeZero",
    "describe",
    "Develop mathematical proofs",
    "divide",
    "divisibility",
    "Draw conclusions from data",
    "Draw valid conclusions",
    "eachIsSolution",
    "Execute procedures systematically",
    "Explain solution strategies",
    "Express mathematical ideas in written form",
    "foot",
    "fundamentalTheoremOfArithmetic",
    "graph",
    "HCF",
    "identify",
    "Identify and recall mathematical concepts",
    "Identify patterns and relationships",
    "Identify relevant information",
    "Identify trends and patterns",
    "independenceOfDimensions",
    "integers",
    "intermediate",
    "Interpret mathematical results in context",
    "Interpret visual information",
    "Justify steps in solutions",
    "know concept",
    "know convention",
    "LCM",
    "lineSegment",
    "locate by setting a point",
    "Make conjectures",
    "Make predictions",
    "manyDigit",
    "mark",
    "master",
    "mixedSigns",
    "Modify models as needed",
    "multiply",
    "negativeXTool",
    "negativeYTool",
    "neighboringIntegers",
    "nonNegativeXTool",
    "nonNegativeYTool",
    "nonPositiveXTool",
    "nonPositiveYTool",
    "noSolution",
    "numberLine",
    "oneDigit",
    "oneSolution",
    "orderOfSomeThings",
    "origin",
    "originTool",
    "Plan solution strategies",
    "plot",
    "point",
    "polynomial",
    "position",
    "positiveNumbers",
    "positiveXTool",
    "positiveYTool",
    "powersOfTen",
    "Present mathematical arguments",
    "primeFactorization",
    "primeNumbers",
    "prove",
    "randomSigns",
    "rationalNumbers",
    "Read and interpret mathematical expressions",
    "read coordinates",
    "realNumbers",
    "Recognize examples and non-examples",
    "Reflect on alternative approaches",
    "Represent data graphically",
    "Represent information using tables, charts, graphs",
    "resultAbsZeroToHundred",
    "resultAbsZeroToHundredTousand",
    "resultAbsZeroToMillion",
    "resultAbsZeroToTen",
    "resultAbsZeroToTenTousand",
    "resultAbsZeroToTousand",
    "Select appropriate mathematical tools",
    "sign",
    "someSolution",
    "spot",
    "subtract",
    "theNumberOne",
    "theNumberZero",
    "threeDigit",
    "Transform between representations",
    "Translate between different representations",
    "twoDigit",
    "understand concept",
    "Understand geometric relationships",
    "Understand problem statements",
    "unit",
    "unknownNumber",
    "Use mathematical vocabulary correctly",
    "Use spatial reasoning",
    "Validate model effectiveness",
    "vector",
    "Verify logical consistency",
    "Verify solutions",
    "Visualize 3D objects",
    "x-direction",
    "y-direction"
  ]
} as const satisfies JSONSchema
