import type { JSONSchema } from "json-schema-to-ts";
import Point2 from '../Point2'
import Flag from '../Flag'
import Sprite from '../Sprite'

//TODO: Have this file autogenerated by Mastory module
export default {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "oneOf": [
    {
      "items": [
        {
          "const": "Point2"
        },
        {
          "$ref": "../Point2.json"
        } as unknown as typeof Point2
      ]
    },
    {
      "items": [
        {
          "const": "Sprite"
        },
        {
          "$ref": "../Sprite.json"
        } as unknown as typeof Sprite
      ]
      // },
      // {
      //   "items": [
      //     {
      //       "const": "Flag"
      //     },
      //     {
      //       "$ref": "../Flag.json"
      //     } as unknown as typeof Flag
      //   ]
    }
  ],
  "minItems": 2,
  "maxItems": 2
} as const satisfies JSONSchema